"""empty message

Revision ID: ccec9b88adbd
Revises: fdf645e92081
Create Date: 2022-05-04 14:40:21.767029

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ccec9b88adbd'
down_revision = 'fdf645e92081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'Characters_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('characters', 'gender',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('characters', 'movies',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('characters', 'eye_color',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('characters', 'height',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('characters', 'hair_color',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('characters', 'birth_year',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('characters', 'mass',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('characters', 'homeworld',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.drop_index('Characters_name', table_name='characters')
    op.drop_index('Characters_name_2', table_name='characters')
    op.alter_column('favorite', 'characters',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('favorite', 'planets',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.drop_index('characters', table_name='favorite')
    op.drop_index('characters_2', table_name='favorite')
    op.alter_column('planets', 'planet_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('planets', 'diameter',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planets', 'rotation_period',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planets', 'gravity',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planets', 'population',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planets', 'climate',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('planets', 'terrian',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('planets', 'surface_water',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index('diameter', table_name='planets')
    op.drop_index('diameter_2', table_name='planets')
    op.drop_index('planet_name', table_name='planets')
    op.drop_index('planet_name_2', table_name='planets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('planet_name_2', 'planets', ['planet_name'], unique=False)
    op.create_index('planet_name', 'planets', ['planet_name'], unique=False)
    op.create_index('diameter_2', 'planets', ['diameter'], unique=False)
    op.create_index('diameter', 'planets', ['diameter'], unique=False)
    op.alter_column('planets', 'surface_water',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('planets', 'terrian',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('planets', 'climate',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('planets', 'population',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('planets', 'gravity',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('planets', 'rotation_period',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('planets', 'diameter',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('planets', 'planet_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.create_index('characters_2', 'favorite', ['characters'], unique=False)
    op.create_index('characters', 'favorite', ['characters'], unique=False)
    op.alter_column('favorite', 'planets',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('favorite', 'characters',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.create_index('Characters_name_2', 'characters', ['Characters_name'], unique=False)
    op.create_index('Characters_name', 'characters', ['Characters_name'], unique=False)
    op.alter_column('characters', 'homeworld',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('characters', 'mass',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('characters', 'birth_year',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('characters', 'hair_color',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('characters', 'height',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('characters', 'eye_color',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('characters', 'movies',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('characters', 'gender',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('characters', 'Characters_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
